[package]
name = "chidian-core"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = "0.5.1"
nom = "8.0.0"
once_cell = "1.21.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
