name: tests
on: [pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install uv
        uses: yezz123/setup-uv@v4
      - name: Install dependencies
        run: uv sync --dev
      - name: Run tests
        run: uv run pytest
